### PR TITLE
correct location of README.md file

### PR DESCRIPTION
**Pull request by akt114**

### CODE REVIEW

**Comment by kaustubh-karkare** [comment]
Thanks for pointing out that the messaging here could be improved, it inspired me to create a proper readme file at the top level (will update soon). Given that, I'm going to close this PR.

Btw, there are readme.md files inside both the assignments & solutions directory.

**Comment by akt114** [comment]
Hello Sir,

Glad that it helped you.
It was me first time contributing towards open source, so I'm happy about
it.

Also, I'd like to tell you that I'm currently a pre final year student of
BIT MESRA and I'm from ECE too who's been into coding and development since
2 years.

I was also the finance coordinator of HACK-A-BIT this year and I had been
waiting to meet you specifically but unfortunately I wasn't well during the
hackathon days and so couldn't meet you.

So please if you could tell me any way so that I can interact with you for
some time.?

I had also sent you connection request on LinkedIn "Amit Tiwary" long back.
Can you please accept it so that we get connected?

I want to gain insights from you and it would definitely help me. Looking
forward to hearing from you.

Thanks and Regards,
Amit Tiwary,
+91 8210392169.

**Comment by kaustubh-karkare** [comment]
Send me a message on Facebook :)

**Comment by akt114** [comment]
Sure I will :)
Thank you so much.

**Pull request closed without merging**
